config/routes.rb
Rails.application.routes.draw do

  get "users/show", to: "users#show", as: :user
  get "users/data", to: "users#data"
  get "users/languages", to: "users#languages"

  root to: "dashboards#index"
  get "auth/github/callback", to: "sessions#create"
  get "signout", to: "sessions#destroy", as: :signout

end

app/models/github.rb
class Github
  
  def initialize(user)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :username, :uid, presence: true

  def client
    @client ||= Octokit::Client.new(access_token: self.token)
  end

  def event_count
    @event_count = @events.group(:type).count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    oauth_attrs       = request.env['omniauth.auth']
    @user = User.find_or_initialize_by(uid:params[:uid])
    @user.username    = oauth_attrs.info.nickname
    @user.email       = oauth_attrs.info.email
    @user.avatar_url  = oauth_attrs.info.image
    @user.token       = oauth_attrs.credentials.token
    @user.uid         = oauth_attrs.uid
    @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @github_user = current_user.client.user
  end

  def data
    @events = current_user.client.user_events(current_user.username, :per_page => 300)
    @events = @events.group_by do |type|
      type["type"]
    end
    render json: @events
  end

  def languages
    @languages = current_user.client.repositories
    @languages = @languages.group_by do |language|
      language["language"]
    end
    render json: @languages
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.erb
  <div class="container">
    <div class="col-lg-12 test-center v-center">
      <div class="row">
        <h1>Don't just Github. Visualize Github!</h1>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitDashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="color-container">
    <div class="container">
      <div class="row">
        <div class="navbar navbar-default">
          <ul>
            <% if current_user %>
              <li>Signed in as <%= current_user.username %>!</li>
              <li class="btn btn-primary navbar-btn"><%= link_to "Home", root_path %></li>
              <li class="btn btn-info navbar-btn"><%= link_to "My Dashboard", user_path %></li>
              <li class="btn btn-danger navbar-btn"><%= link_to "Sign out", signout_path %></li>
            <% else %>
              <li class="btn btn-primary navbar-btn"><%= link_to "Sign In With Github", "/auth/github" %></li>
            <% end %>
          </ul>
        </div>
      </div>

<%= yield %>

    </div>
  </div>
</body>
</html>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6 col-md-offset-3 col-md-6">
      <div class="well well-sm">
          <div class="col-sm-6 col-md-6">
            <%= image_tag current_user.avatar_url, class: "img-rounded img-responsive"%>
          </div>
          <div class="col-sm-6 col-md-4">
            <h3><%= @github_user.name %></h3>
            <small><%= @github_user.location %></small>
            <p class="user-paragraph"><%= @github_user.email %></p>
            <a href="#{@github_user.html_url}" class="email-link">Github</a>
            <p>Followers: <%= @github_user.followers %></p>
            <p>Following: <%= @github_user.following %></p>
            <p>Total # of Gists: <%= @github_user.public_gists %></p>
            <p>Total # of public_repos: <%= @github_user.public_repos %></p>
          </div>
      </div>
    </div>
  </div>
  <div id="chart-container" class="charts"></div>
  <div id="chart-two" class="charts"></div>

</div>